#!/bin/bash
# update.sh — Regenerate listing + pages for tldrhc from YAML sources
# Usage: ./update.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TLDRHC_BIN="${TLDRHC_BIN:-$HOME/.local/bin/tldrhc}"
TLDRHC_PAGES="${TLDRHC_PAGES:-$HOME/.local/share/tldrhc/pages}"
TLDRHC_CONFIG="${TLDRHC_CONFIG:-$HOME/.config/tldrhc/config.toml}"
REPORTS_DIR="$SCRIPT_DIR/reports"

# ── Source check ──────────────────────────────────────────────────────────

echo "🔍 Checking sources..."

required=(
    "$SCRIPT_DIR/sources.py"
    "$SCRIPT_DIR/generate_listing.py"
    "$SCRIPT_DIR/generate_pages.py"
    "$SCRIPT_DIR/inclusions.yaml"
    "$SCRIPT_DIR/descriptions.yaml"
    "$SCRIPT_DIR/examples.yaml"
)

missing=0
for f in "${required[@]}"; do
    if [ ! -f "$f" ]; then
        echo "  ❌ $f — not found"
        missing=$((missing + 1))
    fi
done

if [ "$missing" -gt 0 ]; then
    echo ""
    echo "❌ $missing source file(s) missing. Aborting."
    exit 1
fi

echo "  ✅ All source files present"
echo ""

# ── Generation ────────────────────────────────────────────────────────────

echo "📡 Generating listing..."
python3 "$SCRIPT_DIR/generate_listing.py"
echo ""

echo "📝 Generating pages..."
python3 "$SCRIPT_DIR/generate_pages.py"
echo ""

# ── Examples diff ──────────────────────────────────────────────────────────

echo "📋 Checking examples.yaml against current commands..."

mkdir -p "$REPORTS_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT="$REPORTS_DIR/examples-diff-$TIMESTAMP.md"

export SCRIPT_DIR REPORTS_DIR

python3 << 'PYEOF'
import os, sys, yaml, datetime
sys.path.insert(0, os.environ['SCRIPT_DIR'])
from sources import get_commands, load_examples

timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
reports_dir = os.environ['REPORTS_DIR']
report_path = os.path.join(reports_dir, f'examples-diff-{timestamp}.md')

# Load current commands
current = set(get_commands())

# Commands in examples.yaml
examples = load_examples() if hasattr(__import__('sources'), 'load_examples') else {}
in_examples = set(examples.keys())

# Orphaned: in examples.yaml but no longer a command
orphaned = sorted(in_examples - current)

# New: in current commands but not in examples.yaml
new_cmds = sorted(current - in_examples)

has_diff = len(orphaned) > 0 or len(new_cmds) > 0

if not has_diff:
    print('  ✅ examples.yaml is up to date — no changes detected')
    sys.exit(0)

# Generate report
lines = []
lines.append('# tldrhc — Examples diff')
lines.append('')
lines.append(f'Generated: {timestamp}')
lines.append('')
lines.append('This file is automatically generated by update.sh.')
lines.append('When new CLI commands appear or commands are removed,')
lines.append('they are listed below. Add or remove entries in examples.yaml')
lines.append('then re-run update.sh. You may delete this file after fixing.')
lines.append('')

if new_cmds:
    lines.append('## ➕ New commands (missing examples)')
    lines.append('')
    for name in new_cmds:
        lines.append(f'- {name}')
    lines.append('')

if orphaned:
    lines.append('## ➖ Orphaned examples (command removed)')
    lines.append('')
    for name in orphaned:
        lines.append(f'- {name}')
    lines.append('')

if new_cmds:
    updated = sorted(current)
else:
    updated = sorted(current)

lines.append('## ✅ Commands with examples')
lines.append('')
lines.append(', '.join(updated))
lines.append('')

report_text = '\n'.join(lines)
with open(report_path, 'w') as f:
    f.write(report_text)

print(f'  ⚠ {len(new_cmds)} new, {len(orphaned)} orphaned — see report')
PYEOF

# If report was generated, show the summary lines
if [ -f "$REPORT" ]; then
    REPORT_SIZE=$(wc -l < "$REPORT")
    if [ "$REPORT_SIZE" -gt 3 ]; then
        echo ""
        echo "   Report: $REPORT"
    fi
fi

echo ""

# ── Copy to runtime ──────────────────────────────────────────────────────

echo "📦 Copying to runtime locations..."

mkdir -p "$TLDRHC_PAGES"
cp "$SCRIPT_DIR/pages/_listing.md" "$TLDRHC_PAGES/_listing.md"
cp "$SCRIPT_DIR/pages/"*.page.md "$TLDRHC_PAGES/"

# ── Ensure runtime config ────────────────────────────────────────────────
mkdir -p "$(dirname "$TLDRHC_CONFIG")"
if [ ! -f "$TLDRHC_CONFIG" ]; then
    cp "$SCRIPT_DIR/config.toml" "$TLDRHC_CONFIG"
    echo "   → Config created at $TLDRHC_CONFIG"
fi

if [ -f "$SCRIPT_DIR/tldrhc" ]; then
    mkdir -p "$(dirname "$TLDRHC_BIN")"
    cp "$SCRIPT_DIR/tldrhc" "$TLDRHC_BIN"
    chmod +x "$TLDRHC_BIN"
fi

# ── Summary ─────────────────────────────────────────────────────────────

page_count=$(ls "$TLDRHC_PAGES"/*.page.md 2>/dev/null | wc -l)

echo ""
echo "✅ tldrhc updated"
echo "   Pages  : $page_count"
echo "   Listing: $TLDRHC_PAGES/_listing.md"
echo "   Wrapper: $TLDRHC_BIN"
echo ""
echo "   tldrhc              — list commands"
echo "   tldrhc backup       — help page for a command"
echo ""
